//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentItemEntity : GameItemEntity
    {
        public EquipmentItemEntity()
        {
            this.Tiers = new HashSet<TierEntity>();
            this.Races = new HashSet<RaceEntity>();
            this.Classes = new HashSet<ClassEntity>();
            this.Enhancers = new HashSet<OtherItemEntity>();
            this.Slot = new ItemSlot();
        }
    
        public int Durability { get; set; }
    
        public ItemSlot Slot { get; set; }
    
        public virtual ICollection<TierEntity> Tiers { get; set; }
        public virtual ICollection<RaceEntity> Races { get; set; }
        public virtual ICollection<ClassEntity> Classes { get; set; }
        public virtual ICollection<OtherItemEntity> Enhancers { get; set; }
    }
}
