//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    
    public partial class ItemSlot
    {
        public int NumberOfSlots { get; set; }
        public NinjaHive.Domain.Enums.BodySlot BodySlot { get; set; }
    }
}
