//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelEntity
    {
        public System.Guid Id { get; set; }
        public int Level { get; set; }
        public int Threshold { get; set; }
    
        public virtual TierEntity Tier { get; set; }
        public virtual StatInfoEntity StatInfo { get; set; }
    }
}
