//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillEntity
    {
        public SkillEntity()
        {
            this.Range = 0;
            this.Radius = 0;
            this.Targets = 1;
            this.Specials = new HashSet<SpecialEntity>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Range { get; set; }
        public int Radius { get; set; }
        public int Targets { get; set; }
        public NinjaHive.Domain.Enums.Target Target { get; set; }
        public bool Friendly { get; set; }
    
        public virtual ICollection<SpecialEntity> Specials { get; set; }
        public virtual StatInfoEntity StatInfo { get; set; }
    }
}
