//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatInfoEntity
    {
        public StatInfoEntity()
        {
            this.Health = 0;
            this.Magic = 0;
            this.Attack = 0;
            this.Defense = 0;
            this.Stamina = 0;
            this.Hunger = 0;
            this.Agility = 0;
            this.Intelligence = 0;
            this.Resistance = 0D;
        }
    
        public System.Guid Id { get; set; }
        public int Health { get; set; }
        public int Magic { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int Stamina { get; set; }
        public int Hunger { get; set; }
        public int Agility { get; set; }
        public int Intelligence { get; set; }
        public double Resistance { get; set; }
    }
}
