//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TierEntity
    {
        public TierEntity()
        {
            this.Levels = new HashSet<LevelEntity>();
            this.Skills = new HashSet<SkillEntity>();
            this.UpgradeIngredients = new HashSet<GameItemEntity>();
            this.CraftingIngredients = new HashSet<GameItemEntity>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Tier { get; set; }
    
        public virtual EquipmentItemEntity EquipmentItem { get; set; }
        public virtual ICollection<LevelEntity> Levels { get; set; }
        public virtual ICollection<SkillEntity> Skills { get; set; }
        public virtual ICollection<GameItemEntity> UpgradeIngredients { get; set; }
        public virtual ICollection<GameItemEntity> CraftingIngredients { get; set; }
    }
}
