//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaHive.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NinjaHive.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},&lt;br/&gt;&lt;br/&gt;
        ///
        ///Please confirm your account for NinjaHive by clicking &lt;a href=&quot;{1}&quot;&gt;here&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///If you cannot see the link, copy the following URL into your browser:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///{1}
        ///
        ///
        ///&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Your password is: &lt;b&gt;{2}&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Regards,&lt;br/&gt;&lt;br/&gt;
        ///
        ///The NinjaHive system.
        /// </summary>
        internal static string AccountConfirmationMailTemplate {
            get {
                return ResourceManager.GetString("AccountConfirmationMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},&lt;br/&gt;&lt;br/&gt;
        ///
        ///A NinjaHive admin has provided a password reset for you.&lt;br/&gt;
        ///Click &lt;a href=&quot;{1}&quot;&gt;here&lt;/a&gt; to reset your password.&lt;br/&gt;&lt;br/&gt;
        ///
        ///If you cannot see the link, copy the following URL into your browser:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///{1}
        ///
        ///
        ///
        ///&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Regards,&lt;br/&gt;&lt;br/&gt;
        ///
        ///The NinjaHive system.
        /// </summary>
        internal static string ResetPasswordMailTemplate {
            get {
                return ResourceManager.GetString("ResetPasswordMailTemplate", resourceCulture);
            }
        }
    }
}
